# fly.toml app configuration file generated for tradingview-apiservice on 2025-02-08T13:38:22+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tradingview-apiservice'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "stockmomentum-data"
  destination = "/data"